// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgcrkibbcantkobqlaai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnY3JraWJiY2FudGtvYnFsYWFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTA4OTIsImV4cCI6MjA2ODE2Njg5Mn0.b6cO5qtREVYS8rwfL2CuGU4s501UVto3etAeSoAkwV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});